\ProvidesClass{kjgsatzung}[2020/04/26 Satzung class]
\LoadClass{article}
\NeedsTeXFormat{LaTeX2e}

%------------------------------------
%   Required Packages
%------------------------------------
\RequirePackage{xcolor}
%------------------------------------
%    Farben
%------------------------------------

\definecolor{weiß}{RGB}{255,255,255}
\definecolor{kjggrau}{RGB}{119,120,123}
\definecolor{kjghellgrau}{RGB}{192,192,192}
\definecolor{kjgblau}{RGB}{54,95,145}
\definecolor{kjgtuerkis}{RGB}{0, 181,190}


